### ISSUE TITLE
Probable dependency issue: Unable to npm start

### ISSUE THREAD

**Issue by nadin3amanda** [nadin3amanda/Test-app#3]
![image](https://user-images.githubusercontent.com/85320612/139640098-23bef7d6-1761-44dd-92c6-4f2acb9613e9.png)

**Comment by ChrisLowe-Takor** [comment]
Try `npm install`.   If that doesn't help delete the `node_modules` directory and run `npm install` again.

**Comment by nadin3amanda** [comment]
Thanks Chris. I did that and encountered this 
![image](https://user-images.githubusercontent.com/85320612/139649724-e225fc4a-590a-4710-b91c-79c587e81eaa.png)

I've done steps 1 to 5 and did an npm audit fix --force.

It's now working. Thank you! :D
